/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rjpqkUiu4CJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Checkbox } from "@/components/ui/checkbox"

export function PagMapa() {
  return (
    (<div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <h1 className="text-2xl font-bold">Interactive Map</h1>
      </header>
      <div className="flex flex-1 flex-col md:flex-row">
        <div className="w-full md:w-64 bg-background border-r">
          <div className="p-4 space-y-4">
            <Button className="w-full">
              <PlusIcon className="w-5 h-5 mr-2" />
              Add Stop
            </Button>
            <Button className="w-full">
              <FilePenIcon className="w-5 h-5 mr-2" />
              Edit Route
            </Button>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between w-full">
                <span>Preferences</span>
                <ChevronDownIcon className="w-5 h-5" />
              </CollapsibleTrigger>
              <CollapsibleContent>
                <div className="space-y-2">
                  <div className="flex items-center">
                    <Checkbox />
                    <span className="ml-2">Show Traffic</span>
                  </div>
                  <div className="flex items-center">
                    <Checkbox />
                    <span className="ml-2">Show Landmarks</span>
                  </div>
                  <div className="flex items-center">
                    <Checkbox />
                    <span className="ml-2">Show Public Transportation</span>
                  </div>
                </div>
              </CollapsibleContent>
            </Collapsible>
          </div>
        </div>
        <div className="flex-1">
          <div className="w-full h-full" />
        </div>
      </div>
    </div>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function FilePenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
