/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/B827je4k367
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"
import { Pie, PieChart, CartesianGrid, XAxis, Line, LineChart } from "recharts"

export function RutaReporte() {
  return (
    (<div className="flex flex-col w-full min-h-screen bg-background">
      <header
        className="flex items-center h-16 px-4 border-b border-muted/20 shrink-0 md:px-6">
        <nav
          className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link
            href="#"
            className="flex items-center gap-2 text-lg font-semibold md:text-base"
            prefetch={false}>
            <BusIcon className="w-6 h-6" />
            <span className="sr-only">Panel de control de la flota de autobuses</span>
          </Link>
          <Link href="#" className="font-bold" prefetch={false}>
            Resumen
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Incidentes
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Rutas
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Conductores
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Buscar autobuses..."
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]" />
            </div>
          </form>
          <Button variant="ghost" size="icon" className="rounded-full">
            <img
              src="/placeholder.svg"
              width="32"
              height="32"
              className="rounded-full"
              alt="Avatar"
              style={{ aspectRatio: "32/32", objectFit: "cover" }} />
            <span className="sr-only">Alternar menú de usuario</span>
          </Button>
        </div>
      </header>
      <main
        className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Autobuses activos</CardTitle>
              <BusIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">234</div>
              <p className="text-xs text-muted-foreground">+5.2% respecto al mes pasado</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Autobuses inactivos</CardTitle>
              <BusIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">12</div>
              <p className="text-xs text-muted-foreground">-1.8% respecto al mes pasado</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Hora de inicio promedio</CardTitle>
              <ClockIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">6:15 AM</div>
              <p className="text-xs text-muted-foreground">+10 min respecto al mes pasado</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Hora de finalización promedio</CardTitle>
              <ClockIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">8:45 PM</div>
              <p className="text-xs text-muted-foreground">+15 min respecto al mes pasado</p>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-card rounded-lg p-4">
                <h3 className="text-sm font-medium mb-2">Porcentaje de usuarios por ruta</h3>
                <PiechartcustomChart className="aspect-[16/9]" />
              </div>
              <div className="bg-card rounded-lg p-4">
                <h3 className="text-sm font-medium mb-2">Autobuses activos por ruta</h3>
                <LinechartChart className="aspect-[16/9]" />
              </div>
              <div className="bg-card rounded-lg p-4">
                <h3 className="text-sm font-medium mb-2">Evolución de las horas de servicio</h3>
                <LinechartChart className="aspect-[16/9]" />
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Incidentes y tráfico</CardTitle>
              <BadgeAlertIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Accidentes</div>
                  <div className="text-muted-foreground">12</div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">Averías</div>
                  <div className="text-muted-foreground">8</div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">Retrasos de tráfico</div>
                  <div className="text-muted-foreground">24</div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="font-medium">Cierres de carreteras</div>
                  <div className="text-muted-foreground">6</div>
                </div>
              </div>
              <Separator className="my-4" />
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <Button variant="outline" size="sm">
                    <FilterIcon className="w-4 h-4" />
                    Filtrar
                  </Button>
                  <Button variant="outline" size="sm">
                    <ImportIcon className="w-4 h-4" />
                    Exportar
                  </Button>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Autobús</TableHead>
                      <TableHead>Incidente</TableHead>
                      <TableHead>Ubicación</TableHead>
                      <TableHead>Hora</TableHead>
                      <TableHead>Estado</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-medium">BUS-123</TableCell>
                      <TableCell>Accidente</TableCell>
                      <TableCell>Calle Principal y 5ta Avenida</TableCell>
                      <TableCell>9:15 AM</TableCell>
                      <TableCell>
                        <Badge variant="secondary">Resuelto</Badge>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">BUS-456</TableCell>
                      <TableCell>Avería</TableCell>
                      <TableCell>Avenida del Parque y 12a Calle</TableCell>
                      <TableCell>2:30 PM</TableCell>
                      <TableCell>
                        <Badge variant="outline">Pendiente</Badge>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">BUS-789</TableCell>
                      <TableCell>Retraso de tráfico</TableCell>
                      <TableCell>Broadway y 42a Calle</TableCell>
                      <TableCell>5:45 PM</TableCell>
                      <TableCell>
                        <Badge variant="secondary">Resuelto</Badge>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell className="font-medium">BUS-321</TableCell>
                      <TableCell>Cierre de carretera</TableCell>
                      <TableCell>Calle del Olmo y 7a Avenida</TableCell>
                      <TableCell>11:00 AM</TableCell>
                      <TableCell>
                        <Badge variant="outline">Pendiente</Badge>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Comentarios de los conductores</CardTitle>
              <WebcamIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="grid gap-6">
                <div className="flex items-start gap-4">
                  <Avatar className="border w-10 h-10">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">Juan Pérez</div>
                      <div className="text-xs text-muted-foreground">Hace 2 días</div>
                    </div>
                    <div>
                      La nueva ruta en la 5a Avenida está causando muchos retrasos. ¿Podemos ajustar el horario?
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="ghost" size="sm">
                        <ThumbsUpIcon className="w-4 h-4" />
                        Me gusta
                      </Button>
                      <Button variant="ghost" size="sm">
                        <ReplyIcon className="w-4 h-4" />
                        Responder
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="border w-10 h-10">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>SM</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1">
                    <div className="flex items-center gap-2">
                      <div className="font-medium">Sara Martínez</div>
                      <div className="text-xs text-muted-foreground">Hace 1 semana</div>
                    </div>
                    <div>
                      Los nuevos modelos de autobuses son mucho más cómodos para los pasajeros. ¡Buen trabajo con las
                      mejoras!
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="ghost" size="sm">
                        <ThumbsUpIcon className="w-4 h-4" />
                        Me gusta
                      </Button>
                      <Button variant="ghost" size="sm">
                        <ReplyIcon className="w-4 h-4" />
                        Responder
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Distribución de autobuses por ruta</CardTitle>
              <MapIcon className="w-4 h-4 text-muted-foreground" />
            </CardHeader>
            <CardContent className="grid grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="flex items-center justify-between">
                <div>Ruta A</div>
                <div className="text-muted-foreground">45</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Ruta B</div>
                <div className="text-muted-foreground">32</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Ruta C</div>
                <div className="text-muted-foreground">28</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Ruta D</div>
                <div className="text-muted-foreground">19</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Ruta E</div>
                <div className="text-muted-foreground">14</div>
              </div>
              <div className="flex items-center justify-between">
                <div>Ruta F</div>
                <div className="text-muted-foreground">11</div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>)
  );
}

function BadgeAlertIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>)
  );
}


function BusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 6v6" />
      <path d="M15 6v6" />
      <path d="M2 12h19.6" />
      <path
        d="M18 18h3s.5-1.7.8-2.8c.1-.4.2-.8.2-1.2 0-.4-.1-.8-.2-1.2l-1.4-5C20.1 6.8 19.1 6 18 6H4a2 2 0 0 0-2 2v10h3" />
      <circle cx="7" cy="18" r="2" />
      <path d="M9 18h5" />
      <circle cx="16" cy="18" r="2" />
    </svg>)
  );
}


function ClockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>)
  );
}


function FilterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>)
  );
}


function ImportIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 3v12" />
      <path d="m8 11 4 4 4-4" />
      <path
        d="M8 5H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-4" />
    </svg>)
  );
}


function LinechartChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}>
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}>
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)} />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line
            dataKey="desktop"
            type="natural"
            stroke="var(--color-desktop)"
            strokeWidth={2}
            dot={false} />
        </LineChart>
      </ChartContainer>
    </div>)
  );
}


function MapIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </svg>)
  );
}


function PiechartcustomChart(props) {
  return (
    (<div {...props}>
      <ChartContainer
        config={{
          visitors: {
            label: "Visitors",
          },
          chrome: {
            label: "Chrome",
            color: "hsl(var(--chart-1))",
          },
          safari: {
            label: "Safari",
            color: "hsl(var(--chart-2))",
          },
          firefox: {
            label: "Firefox",
            color: "hsl(var(--chart-3))",
          },
          edge: {
            label: "Edge",
            color: "hsl(var(--chart-4))",
          },
          other: {
            label: "Other",
            color: "hsl(var(--chart-5))",
          },
        }}>
        <PieChart>
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Pie
            data={[
              { browser: "chrome", visitors: 275, fill: "var(--color-chrome)" },
              { browser: "safari", visitors: 200, fill: "var(--color-safari)" },
              { browser: "firefox", visitors: 187, fill: "var(--color-firefox)" },
              { browser: "edge", visitors: 173, fill: "var(--color-edge)" },
              { browser: "other", visitors: 90, fill: "var(--color-other)" },
            ]}
            dataKey="visitors"
            nameKey="browser" />
        </PieChart>
      </ChartContainer>
    </div>)
  );
}


function ReplyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="9 17 4 12 9 7" />
      <path d="M20 18v-2a4 4 0 0 0-4-4H4" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ThumbsUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7 10v12" />
      <path
        d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>)
  );
}


function WebcamIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>)
  );
}
